### ISSUE TITLE
Where should I init ksql query?

### ISSUE THREAD

**Issue by rightx2** [masfworld/cdc_deltaLake#4]
There is a query in `retail.sql` for `ksqldb-server` but I have no idea where should I run those query.

```
CREATE SOURCE CONNECTOR retail_reader WITH (
    'connector.class' = 'io.debezium.connector.postgresql.PostgresConnector',
    'database.hostname' = 'postgres',
    'database.port' = '5432',
    'database.user' = 'postgres-user',
    'database.password' = 'postgres-pw',
    'database.dbname' = 'retail',
    'database.server.name' = 'retail',
    'table.whitelist' = 'public.customers,public.orders',
    'transforms' = 'unwrap',
    'transforms.unwrap.type' = 'io.debezium.transforms.ExtractNewRecordState',
    'transforms.unwrap.drop.tombstones' = 'false',
    'transforms.unwrap.delete.handling.mode' = 'rewrite'
);

INSERT INTO customers (id, name) VALUES (-1, 'test');
INSERT INTO orders (id, product, quantity, customer_id) VALUES (-1, -100, 0, -2);

CREATE STREAM stream_customers WITH (KAFKA_TOPIC='retail.public.customers', value_format='avro');

CREATE STREAM stream_customers_json 
WITH (KAFKA_TOPIC='stream_customers_json', VALUE_FORMAT='json') 
AS SELECT * FROM stream_customers;

CREATE STREAM stream_orders WITH (KAFKA_TOPIC='retail.public.orders', value_format='avro');

CREATE STREAM stream_orders_json 
WITH (KAFKA_TOPIC='stream_orders_json', VALUE_FORMAT='json') 
AS SELECT * FROM stream_orders;

```

What I've tried:
- Copy the sql statement to `ksql_query.sql`.
- Volume mount in `ksqldb-server`:
    ```
  ksqldb-server:
    image: confluentinc/ksqldb-server:0.14.0
    hostname: ksqldb-server
    container_name: ksqldb-server
    depends_on:
      - broker
      - schema-registry
    ports:
      - "8088:8088"
    volumes:
      - "./confluent-hub-components/:/usr/share/kafka/plugins/"
      - "./retail_ksql.sql:/home/appuser/retail_ksql.sql"
    ```
- Add environment variable:
    ```KSQL_KSQL_QUERIES_FILE: "/home/appuser/retail_ksql.sql"```

- Got errors:
```
ksqldb-server      | [2021-12-15 06:23:41,574] ERROR Failed to start KSQL (io.confluent.ksql.rest.server.KsqlServerMain:68)
ksqldb-server      | io.confluent.ksql.util.KsqlStatementException: Unsupported statement. Only the following statements are supporting in standalone mode:
ksqldb-server      | CREAETE STREAM AS SELECT
ksqldb-server      | CREATE STREAM
ksqldb-server      | CREATE TABLE
ksqldb-server      | CREATE TABLE AS SELECT
ksqldb-server      | INSERT INTO
ksqldb-server      | REGISTER TYPE
ksqldb-server      | SET
ksqldb-server      | UNSET
ksqldb-server      | Statement: CREATE SOURCE CONNECTOR retail_reader WITH (
ksqldb-server      |     'connector.class' = 'io.debezium.connector.postgresql.PostgresConnector',
ksqldb-server      |     'database.hostname' = 'postgres',
ksqldb-server      |     'database.port' = '5432',
ksqldb-server      |     'database.user' = 'postgres-user',
ksqldb-server      |     'database.password' = 'postgres-pw',
ksqldb-server      |     'database.dbname' = 'retail',
ksqldb-server      |     'database.server.name' = 'retail',
ksqldb-server      |     'table.whitelist' = 'public.customers,public.orders',
ksqldb-server      |     'transforms' = 'unwrap',
ksqldb-server      |     'transforms.unwrap.type' = 'io.debezium.transforms.ExtractNewRecordState',
ksqldb-server      |     'transforms.unwrap.drop.tombstones' = 'false',
ksqldb-server      |     'transforms.unwrap.delete.handling.mode' = 'rewrite'
ksqldb-server      | );
ksqldb-server      |    at io.confluent.ksql.rest.server.StandaloneExecutor$StatementExecutor.execute(StandaloneExecutor.java:310)
ksqldb-server      |    at io.confluent.ksql.rest.server.StandaloneExecutor.executeStatements(StandaloneExecutor.java:218)
ksqldb-server      |    at io.confluent.ksql.rest.server.StandaloneExecutor.validateStatements(StandaloneExecutor.java:202)
ksqldb-server      |    at io.confluent.ksql.rest.server.StandaloneExecutor.processesQueryFile(StandaloneExecutor.java:180)
ksqldb-server      |    at io.confluent.ksql.rest.server.StandaloneExecutor.startAsync(StandaloneExecutor.java:122)
ksqldb-server      |    at io.confluent.ksql.rest.server.KsqlServerMain.tryStartApp(KsqlServerMain.java:91)
ksqldb-server      |    at io.confluent.ksql.rest.server.KsqlServerMain.main(KsqlServerMain.java:66)
```

**Comment by masfworld** [comment]
You can execute that query in Confluent control center which is deployed in the [docker-compose](https://github.com/masfworld/cdc_deltaLake/blob/f919cd291b14248d6c0b45a8a4649666a91b8915/docker-compose.yaml#L157)

**Comment by rightx2** [comment]
@masfworld Thanks! However, when I paste the code like below:
<img width="1191" alt="Screen Shot 2021-12-15 at 6 33 40 PM" src="https://user-images.githubusercontent.com/10606994/146161046-2d5eb2eb-4ffe-4c02-991c-7bac9b29ee85.png">

Got an error again:
```
{
  "@type": "error_entity",
  "statementText": "CREATE SOURCE CONNECTOR retail_reader WITH (\n    'connector.class' = 'io.debezium.connector.postgresql.PostgresConnector',\n    'database.hostname' = 'postgres',\n    'database.port' = '5432',\n    'database.user' = 'postgres-user',\n    'database.password' = 'postgres-pw',\n    'database.dbname' = 'retail',\n    'database.server.name' = 'retail',\n    'table.whitelist' = 'public.customers,public.orders',\n    'transforms' = 'unwrap',\n    'transforms.unwrap.type' = 'io.debezium.transforms.ExtractNewRecordState',\n    'transforms.unwrap.drop.tombstones' = 'false',\n    'transforms.unwrap.delete.handling.mode' = 'rewrite'\n);",
  "errorMessage": "{\"error_code\":500,\"message\":\"Failed to find any class that implements Connector and which name matches io.debezium.connector.postgresql.PostgresConnector, available connectors are: PluginDesc{klass=class org.apache.kafka.connect.tools.MockConnector, name='org.apache.kafka.connect.tools.MockConnector', version='6.1.0-beta201006024150-hf-1', encodedVersion=6.1.0-beta201006024150-hf-1, type=connector, typeName='connector', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.MockSinkConnector, name='org.apache.kafka.connect.tools.MockSinkConnector', version='6.1.0-beta201006024150-hf-1', encodedVersion=6.1.0-beta201006024150-hf-1, type=sink, typeName='sink', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.MockSourceConnector, name='org.apache.kafka.connect.tools.MockSourceConnector', version='6.1.0-beta201006024150-hf-1', encodedVersion=6.1.0-beta201006024150-hf-1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.SchemaSourceConnector, name='org.apache.kafka.connect.tools.SchemaSourceConnector', version='6.1.0-beta201006024150-hf-1', encodedVersion=6.1.0-beta201006024150-hf-1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.VerifiableSinkConnector, name='org.apache.kafka.connect.tools.VerifiableSinkConnector', version='6.1.0-beta201006024150-hf-1', encodedVersion=6.1.0-beta201006024150-hf-1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.VerifiableSourceConnector, name='org.apache.kafka.connect.tools.VerifiableSourceConnector', version='6.1.0-beta201006024150-hf-1', encodedVersion=6.1.0-beta201006024150-hf-1, type=source, typeName='source', location='classpath'}\"}",
  "warnings": []
}
```


Where do you think I have a problem?

**Comment by masfworld** [comment]
@rightx2 , If you check [this line](https://github.com/masfworld/cdc_deltaLake/blob/f919cd291b14248d6c0b45a8a4649666a91b8915/docker-compose.yaml#L85) in [docker compose file](https://github.com/masfworld/cdc_deltaLake/blob/main/docker-compose.yaml), there is a folder which is copied including all the connectors. you need to put in that folder the connectors.
You can download the connectors using confluent-hub:
`confluent-hub install --component-dir confluent-hub-components --no-prompt debezium/debezium-connector-postgresql:1.1.0`

**Comment by rightx2** [comment]
@masfworld Finally, I get all things done. Thanks for your helps :)
